package de.nplay.moderationbot.auditlog.model;

public enum AuditlogType {
    MODERATION_CREATE,
    MODERATION_REVERT,
    MODERATION_DELETE,
    MODERATION_PURGE,
    NOTE_CREATE,
    NOTE_DELETE,
    PERMISSIONS_USER_UPDATE,
    PERMISSIONS_ROLE_UPDATE,
    CONFIG_UPDATE,
    SLOWMODE_SET,
    SLOWMODE_REMOVE,
    SPIELERSUCHE_AUSSCHLUSS,
    SPIELERSUCHE_FREIGABE
}
