services:
  nplay-moderation-bot:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    volumes:
      - ./src:/home/node/app/src
    container_name: nplay-moderation-bot
    command: npm run start
