version: "3"

services:
  postgres:
    image: postgres
    container_name: nplay-moderation-database
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE}
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  bot:
    build:
      context: .
      dockerfile: Dockerfile
    image: nplay-bot
    container_name: nplay-bot
    restart: on-failure
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - BOT_GUILD=${BOT_GUILD}
      - DATABASE_URL=${DATABASE_URL}
